SELECT 
    i.ITEM_ID,
    i.ITEM_NAME,
    i.RARITY
FROM ITEM_INFO i
WHERE i.ITEM_ID IN (
    SELECT t.ITEM_ID
    FROM ITEM_TREE t
    JOIN ITEM_INFO p
        ON t.PARENT_ITEM_ID = p.ITEM_ID
    WHERE p.RARITY = 'RARE'
)
ORDER BY i.ITEM_ID DESC;